name: File a bug report
description: |
  This form is for bugs with concrete resolutions. If you don't have a specific resolution in mind, then start a Discussion instead.
labels:
- bug

body:
- type: markdown
  attributes:
    value: |
      Thanks for reporting a bug! This form is for bugs which have concrete resolutions. To ask a question or to brainstorm solutions to a problem, start a [Discussion](https://github.com/arxanas/git-branchless/discussions) instead.

- type: textarea
  id: description
  attributes:
    label: Description of the bug
    description: Include a description of the bug and steps to reproduce the issue.
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: What did you expect to happen?

- type: textarea
  id: actual-behavior
  attributes:
    label: Actual behavior
    description: What actually happened?

- type: input
  id: rustc-version
  attributes:
    label: Version of `rustc`
    description: If this is a build issue, paste the output of `rustc --version` here.
    placeholder: "Example: rustc 1.55.0 (c8dfcfe04 2021-09-06)"
    