contact_links:
  - name: Start a Discussion
    url: https://github.com/arxanas/git-branchless/discussions
    about: Ask questions, suggest features, brainstorm solutions, and so on. Open-ended topics belong here.
